In [72]:

from src.utils.data_utils import load_final_df
from src.analysis.virality_analysis.get_viral_posts import get_viral_posts, plot_viral_posts

df = load_final_df(calculate_rss=True)
df = get_viral_posts(df, virality_percentile=0.98, window_size='60D')

In [73]:
df

,SOURCE_SUBREDDIT,TARGET_SUBREDDIT,POST_ID,TIMESTAMP,LINK_SENTIMENT,source_type,Num_characters,Num_characters_no_space,Frac_alpha,Frac_digits,Frac_uppercase,Frac_whitespace,Frac_special,Num_words,Num_unique_words,Num_long_words,Avg_word_length,Num_unique_stopwords,Frac_stopwords,Num_sentences,Num_long_sentences,Avg_chars_per_sentence,Avg_words_per_sentence,Automated_readability_index,Sentiment_pos_vader,Sentiment_neg_vader,Sentiment_compound_vader,LIWC_Funct,LIWC_Pronoun,LIWC_Ppron,LIWC_I,LIWC_We,LIWC_You,LIWC_SheHe,LIWC_They,LIWC_Ipron,LIWC_Article,LIWC_Verbs,LIWC_AuxVb,LIWC_Past,LIWC_Present,LIWC_Future,LIWC_Adverbs,LIWC_Prep,LIWC_Conj,LIWC_Negate,LIWC_Quant,LIWC_Numbers,LIWC_Swear,LIWC_Social,LIWC_Family,LIWC_Friends,LIWC_Humans,LIWC_Affect,LIWC_Posemo,LIWC_Negemo,LIWC_Anx,LIWC_Anger,LIWC_Sad,LIWC_CogMech,LIWC_Insight,LIWC_Cause,LIWC_Discrep,LIWC_Tentat,LIWC_Certain,LIWC_Inhib,LIWC_Incl,LIWC_Excl,LIWC_Percept,LIWC_See,LIWC_Hear,LIWC_Feel,LIWC_Bio,LIWC_Body,LIWC_Health,LIWC_Sexual,LIWC_Ingest,LIWC_Relativ,LIWC_Motion,LIWC_Space,LIWC_Time,LIWC_Work,LIWC_Achiev,LIWC_Leisure,LIWC_Home,LIWC_Money,LIWC_Relig,LIWC_Death,LIWC_Assent,LIWC_Dissent,LIWC_Nonflu,LIWC_Filler,source_cluster_level_0,target_cluster_level_0,source_cluster_level_1,target_cluster_level_1,source_cluster_level_2,target_cluster_level_2,source_cluster_level_3,target_cluster_level_3,source_cluster_level_4,target_cluster_level_4,approved_at_utc,subreddit,user_reports,saved,mod_reason_title,gilded,clicked,link_flair_richtext,subreddit_name_prefixed,hidden,pwls,link_flair_css_class,downs,top_awarded_type,hide_score,name,quarantine,link_flair_text_color,upvote_ratio,author_flair_background_color,subreddit_type,ups,total_awards_received,author_flair_template_id,is_original_content,is_reddit_media_domain,is_meta,category,link_flair_text,can_mod_post,score,approved_by,is_created_from_ads_ui,edited,author_flair_css_class,gildings,content_categories,is_self,mod_note,created,link_flair_type,wls,removed_by_category,banned_by,domain,allow_live_comments,likes,suggested_sort,banned_at_utc,view_count,archived,no_follow,is_crosspostable,pinned,over_18,all_awardings,awarders,media_only,can_gild,spoiler,locked,author_flair_text,treatment_tags,visited,removed_by,num_reports,distinguished,subreddit_id,author_is_blocked,mod_reason_by,removal_reason,id,is_robot_indexable,num_duplicates,report_reasons,author,discussion_type,num_comments,send_replies,contest_mode,author_flair_text_color,permalink,stickied,url,subreddit_subscribers,created_utc,num_crossposts,mod_reports,is_video,title,selftext,source_supercluster,target_supercluster,virality_rss,moving_avg_virality,moving_std_virality,z_score,is_viral
0,leagueoflegends,teamredditteams,1u4nrps,2013-12-31 16:39:58,1,body,345.0,298.0,0.75652173913,0.0173913043478,0.0869565217391,0.150724637681,0.0753623188406,57.0,53.0,10.0,4.78947368421,15.0,0.315789473684,1.0,1.0,345.0,57.0,35.5778947368,0.073,0.08,0.1748,0.3448275862068966,0.05172413793103448,0.034482758620689655,0.0,0.034482758620689655,0.0,0.0,0.0,0.017241379310344827,0.05172413793103448,0.10344827586206896,0.05172413793103448,0.0,0.10344827586206896,0.0,0.034482758620689655,0.034482758620689655,0.06896551724137931,0.017241379310344827,0.034482758620689655,0.0,0.0,0.10344827586206896,0.0,0.0,0.0,0.05172413793103448,0.017241379310344827,0.034482758620689655,0.0,0.0,0.017241379310344827,0.1896551724137931,0.034482758620689655,0.0,0.034482758620689655,0.034482758620689655,0.0,0.0,0.06896551724137931,0.05172413793103448,0.034482758620689655,0.034482758620689655,0.0,0.0,0.017241379310344827,0.017241379310344827,0.0,0.0,0.0,0.06896551724137931,0.017241379310344827,0.05172413793103448,0.0,0.05172413793103448,0.06896551724137931,0.034482758620689655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALL,ALL,League of Legends,League of Legends,League of Legends,League of Legends,leagueoflegends,teamredditteams,leagueoflegends,teamredditteams,NaN,leagueoflegends,[],False,NaN,0.0,False,[],r/leagueoflegends,False,6.0,NaN,0.0,NaN,False,t3_1u4nrp,False,dark,1.00,NaN,public,1.0,0.0,NaN,False,False,False,NaN,NaN,False,1.0,NaN,False,FALSE,NaN,{},NaN,True,NaN,NaN,text,6.0,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,True,True,False,False,False,[],[],False,False,False,False,NaN,NaN,False,NaN,NaN,NaN,t5_2rfxx,False,NaN,NaN,1u4nrp,False,NaN,NaN,[deleted],NaN,7.0,True,False,dark,/r/leagueoflegends/comments/1u4nrp/deleted_by_...,False,NaN,8289274.0,1.388537e+09,0.0,[],False,[deleted by user],[removed],Gaming & Interactive Entertainment,Gaming & Interactive Entertainment,0.001206,0.001206,NaN,NaN,True
1,theredlion,soccer,1u4qkd,2013-12-31 18:18:37,-1,body,101.0,98.0,0.742574257426,0.019801980198,0.049504950495,0.0594059405941,0.178217821782,14.0,14.0,2.0,5.71428571429,1.0,0.0714285714286,2.0,0.0,49.5,7.0,16.0492857143,0.472,0.0,0.5538,0.06666666666666667,0.06666666666666667,0.06666666666666667,0.06666666666666667,0.0,0.0,0.0,0.0,0.0,0.0,0.06666666666666667,0.0,0.0,0.06666666666666667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.13333333333333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06666666666666667,0.0,0.0,0.06666666666666667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06666666666666667,0.06666666666666667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.06666666666666667,0.0,0.06666666666666667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALL,ALL,Political Philosophy Debates,Global Sports MMA,UK Japan Circlejerk,European Soccer Clubs,theredlion,soccer,theredlion,soccer,NaN,TheRedLion,[],False,NaN,0.0,False,[],r/TheRedLion,False,6.0,NaN,0.0,NaN,False,t3_1u4qkd,False,dark,0.73,NaN,public,5.0,0.0,NaN,False,False,False,NaN,NaN,False,5.0,NaN,False,FALSE,NaN,{},NaN,True,NaN,NaN,text,6.0,NaN,NaN,self.TheRedLion,False,NaN,NaN,NaN,NaN,False,False,True,False,False,[],[],False,False,False,False,Petes not so secret gay lover,NaN,False,NaN,NaN,NaN,t5_2vrbs,False,NaN,NaN,1u4qkd,True,NaN,NaN,HarryBlessKnapp,NaN,7.0,True,False,dark,/r/TheRedLion/comments/1u4qkd/happy_new_years_...,False,https://www.reddit.com/r/TheRedLion/comments/1...,6660.0,1.388539e+09,0.0,[],False,Happy new years you cunts 1,I need your help!!! http://www.reddit.com/r/s...,Politics & Society,Sports & Athletics,7.506380,52.552982,51.499119,-0.874706,False
2,inlandempire,bikela,1u4qlzs,2014-01-01 14:54:35,1,body,85.0,85.0,0.752941176471,0.0235294117647,0.0823529411765,0.0117647058824,0.211764705882,10.0,10.0,2.0,7.2,0.0,0.0,1.0,0.0,85.0,10.0,23.605,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.09090909090909091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.09090909090909091,0.09090909090909091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.09090909090909091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALL,ALL,Religion Military Law,Religion Military Law,Maryland Baltimore Fastfood,Maryland Baltimore Fastfood,inlandempire,bikela,inlandempire,bikela,NaN,InlandEmpire,[],False,NaN,0.0,False,[],r/InlandEmpire,False,6.0,NaN,0.0,NaN,False,t3_1u4qlz,False,dark,0.86,NaN,public,15.0,0.0,NaN,False,False,False,NaN,NaN,False,15.0,NaN,False,1505500588,NaN,{},NaN,True,NaN,NaN,text,6.0,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,False,False,False,[],[],False,False,False,False,NaN,NaN,False,NaN,NaN,NaN,t5_2rjtz,False,NaN,NaN,1u4qlz,False,NaN,NaN,[deleted],NaN,2.0,True,False,dark,/r/InlandEmpire/comments/1u4qlz/help_us_find_h...,False,NaN,119086.0,1.388539e+09,0.0,[],False,Help us find hit and run driver (x-post from /...,[deleted],Politics & Society,Politics & Society,1.259583,9.006819,22.619390,-0.342504,False
3,nfl,cfb,1u4sjvs,2013-12-31 17:37:55,1,body,1124.0,949.0,0.772241992883,0.0017793594306,0.0578291814947,0.179715302491,0.0462633451957,191.0,125.0,34.0,4.62303664921,36.0,0.366492146597,15.0,9.0,73.2,12.7333333333,12.6541535777,0.153,0.026,0.9672,0.5260416666666666,0.109375,0.041666666666666664,0.03125,0.0,0.005208333333333333,0.010416666666666666,0.0,0.06770833333333333,0.057291666666666664,0.15104166666666666,0.09895833333333333,0.015625,0.08333333333333333,0.036458333333333336,0.052083333333333336,0.109375,0.052083333333333336,0.010416666666666666,0.046875,0.005208333333333333,0.0,0.06770833333333333,0.010416666666666666,0.0,0.0,0.052083333333333336,0.041666666666666664,0.010416666666666666,0.010416666666666666,0.0,0.0,0.203125,0.046875,0.0,0.036458333333333336,0.046875,0.015625,0.005208333333333333,0.036458333333333336,0.03125,0.015625,0.010416666666666666,0.0,0.0,0.005208333333333333,0.005208333333333333,0.0,0.0,0.0,0.10416666666666667,0.015625,0.052083333333333336,0.036458333333333336,0.026041666666666668,0.03125,0.020833333333333332,0.0,0.0,0.0,0.0,0.0,0.0,0.020833333333333332,0.005208333333333333,ALL,ALL,Major US Sports,Major US Sports,National Football League,College Sports Basketball,nfl,cfb,nfl,cfb,NaN,nfl,[],False,NaN,0.0,False,[],r/nfl,False,6.0,NaN,0.0,NaN,False,t3_1u4sjv,False,dark,0.69,NaN,public,16.0,0.0,NaN,False,False,False,NaN,NaN,False,16.0,NaN,False,FALSE,NaN,{},NaN,True,NaN,NaN,text,6.0,NaN,NaN,self.nfl,False,NaN,NaN,NaN,NaN,True,False,True,False,False,[],[],False,False,False,False,NaN,NaN,False,NaN,NaN,NaN,t5_2qmg3,False,NaN,NaN,1u4sjv,True,NaN,NaN,primeoflife,NaN,8.0,True,False,NaN,/r/nfl/comments/1u4sjv/xpost_from_cfb_question...,False,https://www.reddit.com/r/nfl/comments/1u4sjv/x...,12559215.0,1.388541e+09,0.0,[],False,XPOST from CFB - QUESTION: Can someone help me...,It was suggested that I cross post [THIS](http...,Sports & Athletics,Sports & Athletics,0.012740,0.012740,NaN,NaN,True
4,playmygame,gamedev,1u4w5ss,2014-01-01 02:51:13,1,body,715.0,622.0,0.777622377622,0.00699300699301,0.0251748251748,0.145454545455,0.0699300699301,119.0,92.0,22.0,4.80672268908,24.0,0.361344537815,6.0,4.0,117.666666667,19.8333333333,16.7862464986,0.139,0.039,0.8906,0.38333333333333336,0.06666666666666667,0.03333333333333333,0.03333333333333333,0.0,0.0,0.0,0.0,0.03333333333333333,0.06666666666666667,0.075,0.05,0.03333333333333333,0.03333333333333333,0.0,0.041666666666666664,0.075,0.08333333333333333,0.0,0.025,0.0,0.0,0.075,0.0,0.0,0.008333333333333333,0.05,0.03333333333333333,0.016666666666666666,0.0,0.008333333333333333,0.0,0.13333333333333333,0.03333333333333333,0.0,0.008333333333333333,0.025,0.0,0.0,0.06666666666666667,0.008333333333333333,0.025,0.016666666666666666,0.008333333333333333,0.0,0.008333333333333333,0.008333333333333333,0.0,0.0,0.0,0.058333333333333334,0.0,0.025,0.041666666666666664,0.05,0.016666666666666666,0.025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008333333333333333,ALL,ALL,Video Game Development,Video Game Development,General Game Development,General Game Development,playmygame,gamedev,playmygame,gamedev,NaN,playmygame,[],False,NaN,0.0,False,[],r/playmygame,False,6.0,NaN,0.0,NaN,False,t3_1u4w5s,False,dark,1.00,NaN,public,9.0,0.0,NaN,False,False,False,NaN,NaN,False,9.0,NaN,False,1388563539,NaN,{},NaN,True,NaN,NaN,text,6.0,NaN,NaN,self.playmygame,False,NaN,NaN,NaN,NaN,False,True,True,False,False,[],[],False,False,False,False,NaN,NaN,False,NaN,NaN,NaN,t5_2v8bh,False,NaN,NaN,1u4w5s,True,NaN,NaN,dkramer,NaN,4.0,True,False,NaN,/r/playmygame/comments/1u4w5s/alpha_cantrips_a...,False,https://www.reddit.com/r/playmygame/comments/1...,112435.0,1.388544e+09,0.0,[],False,[Alpha] Cantrips and Cooldowns,Hey guys! My last New Years resolution was to ...,Gaming & Interactive Entertainment,Gaming & Interactive Entertainment,0.800455,2.716453,6.696848,-0.286104,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858483,seattleshitshow,seattlewa,68iptp,2017-04-27 11:07:31,-1,title,83.0,70.0,0.78313253012,0.0,0.10843373494,0.168674698795,0.0481927710843,15.0,14.0,3.0,4.33333333333,5.0,0.4,1.0,1.0,83.0,15.0,12.132,0.0,0.0,0.0,0.4375,0.125,0.0,0.0,0.0,0.0,0.0,0.0,0.125,0.125,0.0625,0.0625,0.0,0.0625,0.0,0.0,0.125,0.0,0.0,0.0,0.0,0.125,0.0,0.0,0.0,0.0,0.1875,0.0625,0.125,0.0,0.125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.125,0.125,0.0,0.0,0.0,0.1875,0.0625,0.0625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALL,ALL,Space Simulators Games,Political Philosophy Debates,Gaming Clans PVP,Bernie Sanders Politics,seattleshitshow,seattlewa,seattleshitshow,seattlewa,NaN,seattleshitshow,[],False,NaN,0.0,False,[],r/seattleshitshow,False,NaN,NaN,0.0,NaN,False,t3_68iptp,False,dark,0.67,NaN,restricted,1.0,0.0,NaN,False,False,False,NaN,NaN,False,1.0,NaN,False,False,NaN,{},NaN,False,NaN,NaN,text,NaN,NaN,NaN,reddit.com,False,NaN,NaN,NaN,NaN,False,True,False,False,False,[],[],False,False,False,False,Brougham Faithless,NaN,False,NaN,NaN,NaN,t5_3fnvl,False,NaN,NaN,68iptp,False,NaN,NaN,CapitolHillRocks,NaN,2.0,True,False,dark,/r/seattleshitshow/comments/68iptp/this_is_the...,False,https://www.reddit.com/r/SeattleWA/comments/68...,41.0,1.493596e+09,0.0,[],False,This is the kind of quality SeattleWA post tha...,NaN,Gaming & Interactive Entertainment,Politics & Society,238.095238,20.616468,123.592328,1.759646,False
858484,peoplewhosayheck,spiderman,68iqh6s,2017-04-30 16:36:07,1,title,121.0,105.0,0.719008264463,0.0165289256198,0.099173553719,0.140495867769,0.123966942149,19.0,19.0,4.0,4.89473684211,5.0,0.263157894737,1.0,1.0,121.0,19.0,18.0652631579,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.05,0.05,0.0,0.0,0.05,0.0,0.1,0.15,0.05,0.0,0.0,0.05,0.05,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.15,0.0,0.0,0.1,0.05,0.05,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.05,0.15,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALL,ALL,Niche Meta Discussion,Movies TV Media,BDSM Lifestyle Subreddits,Star Wars Marvel TV,peoplewhosayheck,spiderman,peoplewhosayheck,spiderman,NaN,PeopleWhoSayHeck,[],False,NaN,0.0,False,[],r/PeopleWhoSayHeck,False,NaN,NaN,0.0,NaN,False,t3_68iqh6,False,dark,1.00,NaN,restricted,1.0,0.0,NaN,False,False,False,NaN,NaN,False,1.0,NaN,False,False,NaN,{},NaN,False,NaN,NaN,text,NaN,NaN,NaN,reddit.com,False,NaN,NaN,NaN,NaN,False,True,True,False,False,[],[],False,False,False,False,NaN,NaN,False,NaN,NaN,NaN,t5_3gz38,False,NaN,NaN,68iqh6,True,NaN,NaN,PeopleWhoSayHeck,NaN,0.0,True,False,NaN,/r/PeopleWhoSayHeck/comments/68iqh6/heck_if_be...,False,https://www.reddit.com/r/Spiderman/comments/68...,483.0,1.493596e+09,0.0,[],False,`Heck if Ben Reillys reign as Spider-Man didn...,NaN,Reddit Meta & Community,Pop Culture & Media,20.661157,17.318363,90.196217,0.037061,False
858485,vzla,wtf,68iqkcs,2017-04-30 15:50:07,1,title,68.0,58.0,0.764705882353,0.0,0.147058823529,0.161764705882,0.0735294117647,13.0,12.0,1.0,4.0,3.0,0.307692307692,1.0,1.0,68.0,13.0,9.70692307692,0.0,0.0,0.0,0.2857142857142857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.07142857142857142,0.0,0.0,0.0,0.0,0.0,0.0,0.21428571428571427,0.0,0.0,0.07142857142857142,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2857142857142857,0.07142857142857142,0.21428571428571427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALL,ALL,Political Philosophy Debates,Best Of Funny,Global Issues Politics,Unexpected Viral Content,vzla,wtf,vzla,wtf,NaN,vzla,[],False,NaN,0.0,False,"[{'e': 'text', 't': 'Meta'}]",r/vzla,False,6.0,brown,0.0,NaN,False,t3_68iqkc,False,NaN,0.90,NaN,public,8.0,0.0,NaN,False,False,False,NaN,Meta,False,8.0,NaN,False,False,alien,{},NaN,False,NaN,NaN,richtext,6.0,NaN,NaN,np.reddit.com,False,NaN,NaN,NaN,NaN,True,False,True,False,False,[],[],False,False,False,False,Im looking california and feeling venezuela🇻🇪,NaN,False,NaN,NaN,NaN,t5_2sh9s,False,NaN,NaN,68iqkc,True,NaN,NaN,isaacbonyuet,NaN,2.0,True,False,dark,/r/vzla/comments/68iqkc/flash_flood_in_venezue...,False,https://np.reddit.com/r/WTF/comments/68f8av/fl...,178021.0,1.493596e+09,0.0,[],False,Flash flood in Venezuela on the front page (po...,NaN,Politics & Society,Pop Culture & Media,0.449383,18.081767,94.692900,-0.186206,False
858486,denverbroncos,nfl,68iqt8,2017-04-30 16:11:30,-1,title,96.0,79.0,0.770833333333,0.0,0.0729166666667,0.1875,0.0416666666667,19.0,19.0,2.0,3.89473684211,8.0,0.421052631579,1.0,1.0,96.0,19.0,11.8678947368,0.118,0.171,-0.2732,0.45,0.1,0.05,0.0,0.0,0.0,0.05,0.0,0.05,0.05,0.15,0.1,0.0,0.05,0.05,0.05,0.1,0.0,0.0,0.05,0.0,0.05,0.05,0.0,0.0,0.0,0.1,0.05,0.05,0.0,0.05,0.0,0.15,0.0,0.0,0.1,0.05,0.0,0.0,0.0,0.0,0.05,0.05,0.0,0.0,0.05,0.05,0.0,0.0,0.0,0.15,0.0,0.05,0.15,0.0,0.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,0.05,ALL,ALL,Major US Sports,Major US Sports,National Football League,National Football League,denverbroncos,nfl,denverbroncos,nfl,NaN,DenverBroncos,[],False,NaN,0.0,False,[],r/DenverBroncos,False,6.0,NaN,0.0,NaN,False,t3_68iqt8,False,dark,0.82,NaN,public,40.0,0.0,NaN,False,False,False,NaN,NaN,False,40.0,NaN,False,False,SB50,{},NaN,False,NaN,NaN,text,6.0,NaN,NaN,reddit.com,False,NaN,NaN,NaN,NaN,True,False,True,False,False,[],[],False,False,False,False,NaN,NaN,False,NaN,NaN,NaN,t5_2s51j,False,NaN,NaN,68iqt8,True,NaN,NaN,dsty292,NaN,5.0,True,False,dark,/r/DenverBroncos/comments/68iqt8/it_looks_like...,False,https://www.reddit.com/r/nfl/comments/5a7sx7/g...,223018.0,1.493597e+09,0.0,[],False,It looks like Kubiak should be expecting a bag...,NaN,Sports & Athletics,Sports & Athletics,1.793569,4.900500,25.019026,-0.124183,False
858487,shitpoliticssays,politicaldiscussion,68ir4os,2017-04-30 15:14:05,1,title,140.0,122.0,0.8,0.0,0.114285714286,0.135714285714,0.0642857142857,21.0,19.0,5.0,5.42857142857,6.0,0.333333333333,3.0,0.0,46.0,7.0,13.47,0.0,0.127,-0.3875,0.45454545454545453,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.09090909090909091,0.13636363636363635,0.13636363636363635,0.045454545454545456,0.09090909090909091,0.0,0.13636363636363635,0.09090909090909091,0.045454545454545456,0.045454545454545456,0.045454545454545456,0.0,0.0,0.0,0.0,0.0,0.0,0.045454545454545456,0.045454545454545456,0.0,0.0,0.0,0.0,0.09090909090909091,0.0,0.0,0.0,0.0,0.09090909090909091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.045454545454545456,0.0,0.0,0.045454545454545456,0.09090909090909091,0.045454545454545456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALL,ALL,Political Philosophy Debates,Political Philosophy Debates,Mens Rights Drama,Anti Political Spams,shitpoliticssays,politicaldiscussion,shitpoliticssays,politicaldiscussion,NaN,ShitPoliticsSays,[],False,NaN,0.0,False,[],r/ShitPoliticsSays,False,7.0,NaN,0.0,NaN,False,t3_68ir4o,False,dark,0.96,NaN,public,81.0,0.0,NaN,False,False,False,NaN,NaN,False,81.0,NaN,False,False,NaN,{},NaN,False,NaN,NaN,text,7.0,NaN,NaN,np.reddit.com,False,NaN,NaN,NaN,NaN,False,False,True,False,False,[],[],False,False,False,False,NaN,NaN,False,NaN,NaN,NaN,t5_2vcl0,False,NaN,NaN,68ir4o,True,NaN,NaN,ctrocks,NaN,15.0,False,False,NaN,/r/ShitPoliticsSays/comments/68ir4o/the_rncs_b...,False,https://np.reddit.com/r/PoliticalDiscussion/co...,85867.0,1.493597e+09,0.0,[],False,The RNCs brand has never been about honesty. H...,NaN,Politics & Society,Politics & Society,9.433083,18.081048,94.687240,-0.091332,False

In [74]:
import pandas as pd
pd.set_option('display.max_columns', None)

df = df.iloc[:, list(range(92)) + [-1, -6, -7]]
df = df.drop(columns=["SOURCE_SUBREDDIT", "TARGET_SUBREDDIT", "POST_ID", "TIMESTAMP", "source_type"])

In [75]:
question_templates = {
    "LINK_SENTIMENT": "Should the overall link sentiment score be higher or lower than ",
    "Num_characters": "Should the total number of characters in the post be higher or lower than ",
    "Num_characters_no_space": "Should the number of non-space characters be higher or lower than ",
    "Frac_alpha": "Should the fraction of alphabetic characters be higher or lower than ",
    "Frac_digits": "Should the fraction of digits in the text be higher or lower than ",
    "Frac_uppercase": "Should the fraction of UPPERCASE letters be higher or lower than ",
    "Frac_whitespace": "Should the fraction of whitespace characters be higher or lower than ",
    "Frac_special": "Should the fraction of special symbols (punctuation etc.) be higher or lower than ",
    "Num_words": "Should the total number of words in the post be higher or lower than ",
    "Num_unique_words": "Should the number of unique words used be higher or lower than ",
    "Num_long_words": "Should the number of long words be higher or lower than ",
    "Avg_word_length": "Should the average word length be higher or lower than ",
    "Num_unique_stopwords": "Should the number of unique stopwords be higher or lower than ",
    "Frac_stopwords": "Should the fraction of stopwords in the text be higher or lower than ",
    "Num_sentences": "Should the number of sentences in the post be higher or lower than ",
    "Num_long_sentences": "Should the number of long sentences be higher or lower than ",
    "Avg_chars_per_sentence": "Should the average number of characters per sentence be higher or lower than ",
    "Avg_words_per_sentence": "Should the average number of words per sentence be higher or lower than ",
    "Automated_readability_index": "Should the automated readability index be higher or lower than ",
    "Sentiment_pos_vader": "Should the positive VADER sentiment score be higher or lower than ",
    "Sentiment_neg_vader": "Should the negative VADER sentiment score be higher or lower than ",
    "Sentiment_compound_vader": "Should the overall (compound) VADER sentiment score be higher or lower than ",
    "LIWC_Funct": "Should the proportion of function words be more or less than ",
    "LIWC_Pronoun": "Should the proportion of pronouns be more or less than ",
    "LIWC_Ppron": "Should the proportion of personal pronouns be more or less than ",
    "LIWC_I": "Should the proportion of first-person singular \"I\" words be more or less than ",
    "LIWC_We": "Should the proportion of \"we\" (first-person plural) words be more or less than ",
    "LIWC_You": "Should the proportion of \"you\" references be more or less than ",
    "LIWC_SheHe": "Should the proportion of \"she/he\" references be more or less than ",
    "LIWC_They": "Should the proportion of \"they\" references be more or less than ",
    "LIWC_Ipron": "Should the proportion of impersonal pronouns be more or less than ",
    "LIWC_Article": "Should the proportion of articles (e.g., \"a\", \"the\") be more or less than ",
    "LIWC_Verbs": "Should the proportion of verbs in the text be more or less than ",
    "LIWC_AuxVb": "Should the proportion of auxiliary verbs (e.g., \"is\", \"have\") be more or less than ",
    "LIWC_Past": "Should the proportion of past-tense verbs be more or less than ",
    "LIWC_Present": "Should the proportion of present-tense verbs be more or less than ",
    "LIWC_Future": "Should the proportion of future-oriented verbs be more or less than ",
    "LIWC_Adverbs": "Should the proportion of adverbs be more or less than ",
    "LIWC_Prep": "Should the proportion of prepositions be more or less than ",
    "LIWC_Conj": "Should the proportion of conjunctions (e.g., \"and\", \"but\") be more or less than ",
    "LIWC_Negate": "Should the proportion of negations (e.g., \"not\", \"never\") be more or less than ",
    "LIWC_Quant": "Should the proportion of quantifiers (e.g., \"many\", \"few\") be more or less than ",
    "LIWC_Numbers": "Should the proportion of explicit number words be more or less than ",
    "LIWC_Swear": "Should the proportion of swear or profanity terms be more or less than ",
    "LIWC_Social": "Should the proportion of socially oriented words be more or less than ",
    "LIWC_Family": "Should the proportion of family-related words be more or less than ",
    "LIWC_Friends": "Should the proportion of friend-related terms be more or less than ",
    "LIWC_Humans": "Should the proportion of generic human-related words be more or less than ",
    "LIWC_Affect": "Should the proportion of affective (emotion-related) words be more or less than ",
    "LIWC_Posemo": "Should the proportion of positive emotion words be more or less than ",
    "LIWC_Negemo": "Should the proportion of negative emotion words be more or less than ",
    "LIWC_Anx": "Should the proportion of anxiety-related words be more or less than ",
    "LIWC_Anger": "Should the proportion of anger-related words be more or less than ",
    "LIWC_Sad": "Should the proportion of sadness-related words be more or less than ",
    "LIWC_CogMech": "Should the proportion of cognitive mechanism terms be more or less than ",
    "LIWC_Insight": "Should the proportion of insight-related words (e.g., \"think\", \"know\") be more or less than ",
    "LIWC_Cause": "Should the proportion of causation-related words (e.g., \"because\") be more or less than ",
    "LIWC_Discrep": "Should the proportion of discrepancy words (e.g., \"should\", \"would\") be more or less than ",
    "LIWC_Tentat": "Should the proportion of tentative words (e.g., \"maybe\", \"perhaps\") be more or less than ",
    "LIWC_Certain": "Should the proportion of certainty words (e.g., \"always\", \"definitely\") be more or less than ",
    "LIWC_Inhib": "Should the proportion of inhibition-related words (e.g., \"stop\", \"block\") be more or less than ",
    "LIWC_Incl": "Should the proportion of inclusive terms (e.g., \"with\", \"include\") be more or less than ",
    "LIWC_Excl": "Should the proportion of exclusive terms (e.g., \"but\", \"without\") be more or less than ",
    "LIWC_Percept": "Should the proportion of perception-related words be more or less than ",
    "LIWC_See": "Should the proportion of vision-related words (seeing) be more or less than ",
    "LIWC_Hear": "Should the proportion of hearing-related words be more or less than ",
    "LIWC_Feel": "Should the proportion of feeling- or touch-related words be more or less than ",
    "LIWC_Bio": "Should the proportion of general biological process words be more or less than ",
    "LIWC_Body": "Should the proportion of body-related terms be more or less than ",
    "LIWC_Health": "Should the proportion of health-related words be more or less than ",
    "LIWC_Sexual": "Should the proportion of sexual-related words be more or less than ",
    "LIWC_Ingest": "Should the proportion of ingestion-related words (eating, drinking) be more or less than ",
    "LIWC_Relativ": "Should the proportion of relativity-related words (time, space, motion) be more or less than ",
    "LIWC_Motion": "Should the proportion of motion-related words (moving, going) be more or less than ",
    "LIWC_Space": "Should the proportion of space-related words (locations, positions) be more or less than ",
    "LIWC_Time": "Should the proportion of time-related words (e.g., \"today\", \"soon\") be more or less than ",
    "LIWC_Work": "Should the proportion of work-related terms be more or less than ",
    "LIWC_Achiev": "Should the proportion of achievement-related words be more or less than ",
    "LIWC_Leisure": "Should the ratio of leisure-related terms be more or less than ",
    "LIWC_Home": "Should the proportion of home-related words be more or less than ",
    "LIWC_Money": "Should the proportion of money- or finance-related words be more or less than ",
    "LIWC_Relig": "Should the proportion of religion-related words be more or less than ",
    "LIWC_Death": "Should the proportion of death- or mortality-related words be more or less than ",
    "LIWC_Assent": "Should the proportion of assent words (e.g., \"yeah\", \"okay\") be more or less than ",
    "LIWC_Dissent": "Should the proportion of dissent or disagreement words be more or less than ",
    "LIWC_Nonflu": "Should the proportion of non-fluencies (e.g., \"um\", \"uh\") be more or less than ",
    "LIWC_Filler": "Should the proportion of filler words (e.g., \"like\", \"you know\") be more or less than ",
}

In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import _tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

X = df.drop(columns=["is_viral"])
y = df["is_viral"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

clf = DecisionTreeClassifier(
    criterion="gini",
    class_weight="balanced", 
    max_depth=15,
    min_samples_split=2,
    min_samples_leaf=20,
    random_state=42
)

def tree_to_dataframe(clf, X, y):

    tree = clf.tree_

    if hasattr(X, "columns"):
        feature_names = list(X.columns)
    else:
        feature_names = [f"feature_{i}" for i in range(clf.n_features_in_)]

    n_nodes       = tree.node_count
    children_left = tree.children_left
    children_right = tree.children_right
    feature       = tree.feature
    threshold     = tree.threshold

    node_depth = np.zeros(n_nodes, dtype=int)
    is_leaf    = np.zeros(n_nodes, dtype=bool)

    stack = [(0, 0)] 
    while stack:
        node_id, depth = stack.pop()
        node_depth[node_id] = depth

        left = children_left[node_id]
        right = children_right[node_id]

        if left != _tree.TREE_LEAF:
            stack.append((left,  depth + 1))
            stack.append((right, depth + 1))
        else:
            is_leaf[node_id] = True

    weighted_value = tree.value.squeeze()
    if weighted_value.ndim == 1: 
        weighted_value = weighted_value[:, np.newaxis]

    n_node_samples_unweighted = tree.n_node_samples
    weighted_n_node_samples   = getattr(
        tree,
        "weighted_n_node_samples",
        tree.n_node_samples.astype(float)
    )

    X_array = X.values if hasattr(X, "values") else np.asarray(X)
    y_array = np.asarray(y)

    class_to_index = {cls: idx for idx, cls in enumerate(clf.classes_)}
    y_idx = np.vectorize(class_to_index.get)(y_array)

    node_indicator = clf.decision_path(X_array)

    n_classes = len(clf.classes_)
    unweighted_value = np.zeros((n_nodes, n_classes), dtype=int)

    for k in range(n_classes):
        mask = (y_idx == k)
        if not np.any(mask):
            continue
        counts_k = np.asarray(node_indicator[mask].sum(axis=0)).ravel()
        unweighted_value[:, k] = counts_k

    weighted_pred_idx   = weighted_value.argmax(axis=1)
    unweighted_pred_idx = unweighted_value.argmax(axis=1)

    weighted_pred_class   = clf.classes_[weighted_pred_idx]
    unweighted_pred_class = clf.classes_[unweighted_pred_idx]

    df_nodes = pd.DataFrame({
        "node_id": np.arange(n_nodes),
        "level": node_depth,
        "is_leaf": is_leaf,
        "feature_idx": feature,
        "feature_name": [
            feature_names[i] if i != _tree.TREE_UNDEFINED else None
            for i in feature
        ],
        "threshold": threshold,
        "left_child": children_left,
        "right_child": children_right,
        "n_node_samples_unweighted": n_node_samples_unweighted,
        "n_node_samples_weighted": weighted_n_node_samples,
        "weighted_value": list(weighted_value),
        "unweighted_value": list(unweighted_value),
        "pred_class_weighted": weighted_pred_class,
        "pred_class_unweighted": unweighted_pred_class,
    })

    return df_nodes

df_nodes = tree_to_dataframe(clf, X_train, y_train).sort_values(by="level")

c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [77]:
df_nodes

,node_id,level,is_leaf,feature_idx,feature_name,threshold,left_child,right_child,n_node_samples_unweighted,n_node_samples_weighted,weighted_value,unweighted_value,pred_class_weighted,pred_class_unweighted
0,0,0,False,3,Frac_alpha,0.720138,1,946,565065,565064.999996,"[0.500000000003596, 0.5000000000032656]","[553760, 11305]",False,False
946,946,1,False,8,Num_words,5.500000,947,1206,508297,482070.627261,"[0.528335589648111, 0.47166441036279394]","[499199, 9098]",False,False
1,1,1,False,54,LIWC_CogMech,0.042957,2,485,56768,82994.372735,"[0.3354134741647716, 0.6645865258362396]","[54561, 2207]",True,False
1206,1206,2,False,14,Num_sentences,37.500000,1207,2788,479886,443362.809670,"[0.5429056160066132, 0.4570943840034211]","[471777, 8109]",False,False
485,485,2,False,16,Avg_chars_per_sentence,229.932449,486,841,31298,33154.564464,"[0.4708343673044018, 0.5291656326955441]","[30596, 702]",True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1495,15,True,-2,None,-2.000000,-1,-1,121,600.330533,"[0.08413788540973229, 0.9158621145902655]","[99, 22]",True,False
1496,1496,15,True,-2,None,-2.000000,-1,-1,23,11.734772,"[1.0, 0.0]","[23, 0]",False,False
1481,1481,15,True,-2,None,-2.000000,-1,-1,22325,18710.383704,"[0.6006199747565384, 0.39938002524341215]","[22026, 299]",False,False
1482,1482,15,True,-2,None,-2.000000,-1,-1,764,414.280133,"[0.9396741099027968, 0.06032589009719976]","[763, 1]",False,False
1484,1484,15,True,-2,None,-2.000000,-1,-1,97,294.306229,"[0.1508226712067762, 0.8491773287932232]","[87, 10]",True,False

In [90]:
import json
import numpy as np
import pandas as pd
from sklearn.tree import _tree

def tree_df_to_quiz_data(df_nodes, root_id=0):
    df = df_nodes.set_index("node_id")

    def node_key(node_id):
        """Return the string key for a node (question or result)."""
        if df.loc[node_id, "is_leaf"]:
            return f"result_{node_id}"
        else:
            return f"q_{node_id}"

    quiz_data = {}

    for node_id, row in df.iterrows():
        if row["is_leaf"]:
            pred = row.get("pred_class_unweighted", None)
            quiz_data[node_key(node_id)] = {
                "question": f"""Your chance to go viral is {(row['unweighted_value'][1] / sum(row['unweighted_value'])*100):.2f}%\n
                compared to 2% average chance.""",
                "is_leaf": True,
            }
        else:
            left_id = int(row["left_child"])
            right_id = int(row["right_child"])

            feature = row.get("feature_name", "feature")
            threshold = row.get("threshold", None)

            if isinstance(threshold, (int, float, np.floating)):
                thr_str = f"{threshold:.4f}"
            else:
                thr_str = str(threshold)
                
            if (feature.startswith("LIWC")) or (feature.startswith("Frac")):
                thr_str = round(float(thr_str)*100, 3)
                thr_str = f"{str(thr_str)}%"

            question_text = f"{question_templates[feature]} {thr_str}"

            quiz_data[node_key(node_id)] = {
                "question": question_text,
                "option_A": "Lower",   #
                "path_A": node_key(left_id),
                "option_B": "Higher",
                "path_B": node_key(right_id),
                "clusters": "false",
            }

    
    root_key = node_key(root_id)
    if root_key in quiz_data and root_key != "q_start":
        quiz_data["q_start"] = quiz_data.pop(root_key)

    return quiz_data

In [91]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np

def fit_supercluster_trees(
    df,
    label_col,
    max_depth=5,
    class_weight="balanced",
    random_state=42
):

    models = {}

    sources = df["source_supercluster"].unique()
    targets = df["target_supercluster"].unique()

    for src in sources:
        for tgt in targets:
            mask = (
                (df["source_supercluster"] == src) &
                (df["target_supercluster"] == tgt)
            )
            df_sub = df.loc[mask]
            df_sub = df_sub.drop(columns=["source_supercluster", "target_supercluster"])
            X_sub = df_sub.drop(columns=[label_col])
            y_sub = df_sub[label_col].values

            clf = DecisionTreeClassifier(
                max_depth=max_depth,
                class_weight=class_weight,
                random_state=random_state,
            )
            clf.fit(X_sub, y_sub)

            models[(src, tgt)] = clf
            
            df_nodes = tree_to_dataframe(clf, X_sub, y_sub)
            
            quiz = tree_df_to_quiz_data(df_nodes)

            output_path = f"jsons/quiz_data_{src.split('&')[0].replace(' ', '')}_{tgt.split('&')[0].replace(' ', '')}.json" 

            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(quiz, f, indent=2)

    return models


fit_supercluster_trees(df, label_col="is_viral", max_depth=5)

c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\clued\anaconda3\envs\EPFL\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

{('Gaming & Interactive Entertainment',
  'Gaming & Interactive Entertainment'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Gaming & Interactive Entertainment',
  'Sports & Athletics'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Gaming & Interactive Entertainment',
  'Politics & Society'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Gaming & Interactive Entertainment',
  'Technology & Digital Culture'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Gaming & Interactive Entertainment',
  'Lifestyle & Niche Interests'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Gaming & Interactive Entertainment',
  'Pop Culture & Media'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Gaming & Interactive Entertainment',
  'Reddit Meta & Community'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Politics & Society',
  'Gaming & Interactive Entertainment'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Politics & Society',
  'Sports & Athletics'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Politics & Society',
  'Politics & Society'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Politics & Society',
  'Technology & Digital Culture'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Politics & Society',
  'Lifestyle & Niche Interests'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Politics & Society',
  'Pop Culture & Media'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Politics & Society',
  'Reddit Meta & Community'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Sports & Athletics',
  'Gaming & Interactive Entertainment'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Sports & Athletics',
  'Sports & Athletics'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Sports & Athletics',
  'Politics & Society'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Sports & Athletics',
  'Technology & Digital Culture'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Sports & Athletics',
  'Lifestyle & Niche Interests'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Sports & Athletics',
  'Pop Culture & Media'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Sports & Athletics',
  'Reddit Meta & Community'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Technology & Digital Culture',
  'Gaming & Interactive Entertainment'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Technology & Digital Culture',
  'Sports & Athletics'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Technology & Digital Culture',
  'Politics & Society'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Technology & Digital Culture',
  'Technology & Digital Culture'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Technology & Digital Culture',
  'Lifestyle & Niche Interests'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Technology & Digital Culture',
  'Pop Culture & Media'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Technology & Digital Culture',
  'Reddit Meta & Community'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Reddit Meta & Community',
  'Gaming & Interactive Entertainment'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Reddit Meta & Community',
  'Sports & Athletics'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Reddit Meta & Community',
  'Politics & Society'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Reddit Meta & Community',
  'Technology & Digital Culture'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Reddit Meta & Community',
  'Lifestyle & Niche Interests'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Reddit Meta & Community',
  'Pop Culture & Media'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Reddit Meta & Community',
  'Reddit Meta & Community'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Pop Culture & Media',
  'Gaming & Interactive Entertainment'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Pop Culture & Media',
  'Sports & Athletics'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Pop Culture & Media',
  'Politics & Society'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Pop Culture & Media',
  'Technology & Digital Culture'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Pop Culture & Media',
  'Lifestyle & Niche Interests'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Pop Culture & Media',
  'Pop Culture & Media'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Pop Culture & Media',
  'Reddit Meta & Community'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Lifestyle & Niche Interests',
  'Gaming & Interactive Entertainment'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Lifestyle & Niche Interests',
  'Sports & Athletics'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Lifestyle & Niche Interests',
  'Politics & Society'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Lifestyle & Niche Interests',
  'Technology & Digital Culture'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Lifestyle & Niche Interests',
  'Lifestyle & Niche Interests'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Lifestyle & Niche Interests',
  'Pop Culture & Media'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42),
 ('Lifestyle & Niche Interests',
  'Reddit Meta & Community'): DecisionTreeClassifier(class_weight='balanced', max_depth=5, random_state=42)}

In [ ]:
d = df["source_supercluster"].unique()
for cluster in d:
    print(cluster.split('&')[0])

Gaming
Politics
Sports
Technology
Reddit Meta
Pop Culture
Lifestyle

In [64]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

df = df.drop(columns=["source_supercluster", "target_supercluster"])

X = df.drop(columns=["is_viral"])
y = df["is_viral"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

clf = DecisionTreeClassifier(
    criterion="gini",
    class_weight="balanced", 
    max_depth=15,
    min_samples_split=2,
    min_samples_leaf=20,
    random_state=42
)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

[[97338 41103]
 [ 1429  1397]]
              precision    recall  f1-score   support

       False     0.9855    0.7031    0.8207    138441
        True     0.0329    0.4943    0.0616      2826

    accuracy                         0.6989    141267
   macro avg     0.5092    0.5987    0.4412    141267
weighted avg     0.9665    0.6989    0.8055    141267

In [65]:
y_pred_train = clf.predict(X_train)
print(confusion_matrix(y_train, y_pred_train))

[[391780 161980]
 [  2711   8594]]